export const worldCities = [
  "Londres", "París", "Berlín", "Madrid", "Roma", "Ámsterdam", "Viena", "Praga", "Budapest", "Varsovia",
  "Atenas", "Lisboa", "Dublín", "Oslo", "Estocolmo", "Copenhague", "Helsinki", "Bruselas", "Zúrich", "Ginebra",
  "Múnich", "Fráncfort", "Hamburgo", "Milán", "Venecia", "Florencia", "Nápoles", "Sevilla", "Barcelona", "Valencia",
  "Oporto", "Cracovia", "Tallin", "Riga", "Vilna", "Luxemburgo", "Mónaco", "Liubliana", "Bratislava", "Belgrado",
  "Sarajevo", "Podgorica", "Tirana", "Skopie", "Chisinau", "Minsk", "Kiev", "Járkov", "Odesa", "Leópolis",
  "Bucarest", "Sofía", "Ereván", "Tiflis", "Bakú", "Reikiavik", "Berna", "Lyon", "Marsella", "Toulouse",
  "Niza", "Nantes", "Estrasburgo", "Burdeos", "Bilbao", "Málaga", "Zaragoza", "Alicante", "Granada", "Córdoba",
  "Bolonia", "Turín", "Palermo", "Génova", "Verona", "Salzburgo", "Innsbruck", "Rotterdam", "Amberes", "Gante",
  "Tokio", "Osaka", "Kioto", "Seúl", "Pekín", "Shanghái", "Hong Kong", "Taipéi", "Bangkok", "Singapur",
  "Kuala Lumpur", "Yakarta", "Manila", "Hanói", "Saigón", "Nueva Delhi", "Mumbai", "Kolkata", "Chennai", "Bangalore",
  "Hyderabad", "Islamabad", "Karachi", "Lahore", "Dhaka", "Katmandú", "Colombo", "Malé", "Timbu", "Kabul",
  "Teherán", "Bagdad", "Riad", "Yeda", "Dubái", "Abu Dabi", "Doha", "Kuwait", "Mascate", "Manama",
  "Beirut", "Damasco", "Amán", "Jerusalén", "Tel Aviv", "Ankara", "Estambul", "Antalya", "Nicosia", "Astaná",
  "Almaty", "Taskent", "Biskek", "Dusambé", "Asjabad", "Ulán Bator", "Pionyang", "Macao", "Nagoya", "Fukuoka",
  "Sapporo", "Busán", "Incheon", "Guangzhou", "Shenzhen", "Chengdu", "Chongqing", "Xi'an", "Wuhan", "Nankín",
  "Nueva York", "Los Ángeles", "Chicago", "Houston", "Phoenix", "Filadelfia", "San Antonio", "San Diego", "Dallas", "San José",
  "Austin", "Jacksonville", "San Francisco", "Columbus", "Indianápolis", "Seattle", "Denver", "Washington DC", "Boston", "Nashville",
  "El Paso", "Detroit", "Portland", "Las Vegas", "Oklahoma City", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque",
  "Tucson", "Fresno", "Sacramento", "Kansas City", "Atlanta", "Omaha", "Colorado Springs", "Raleigh", "Miami", "Oakland",
  "Mineápolis", "Tulsa", "Wichita", "Nueva Orleans", "Toronto", "Montreal", "Vancouver", "Ottawa", "Calgary", "Edmonton",
  "Winnipeg", "Quebec", "Ciudad de México", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Ciudad Juárez", "Zapopan",
  "La Habana", "Santiago de Cuba", "Kingston", "Nasáu", "Puerto Príncipe", "Santo Domingo", "San Juan", "Ciudad de Guatemala", "Ciudad de Belice", "San Salvador",
  "Tegucigalpa", "Managua", "Panamá", "Cancún", "Mérida", "San Luis Potosí", "Querétaro", "Toluca", "Aguascalientes",
  "Bogotá", "Medellín", "Cali", "Barranquilla", "Caracas", "Maracaibo", "Georgetown", "Paramaribo", "Cayena",
  "Quito", "Guayaquil", "Lima", "Arequipa", "Trujillo", "Cusco", "La Paz", "Sucre", "Santa Cruz", "Asunción",
  "Santiago", "Valparaíso", "Buenos Aires", "Rosario", "Mendoza", "Montevideo", "Brasilia", "Río de Janeiro", "São Paulo",
  "Salvador", "Fortaleza", "Belo Horizonte", "Manaos", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia", "Guarulhos",
  "Campinas", "São Luís", "Maceió", "Duque de Caxias", "Natal", "Teresina", "São Bernardo do Campo", "Campo Grande", "João Pessoa", "Jaboatão dos Guararapes",
  "El Cairo", "Alejandría", "Giza", "Lagos", "Kano", "Ibadán", "Kinshasa", "Johannesburgo", "Ciudad del Cabo", "Durban",
  "Pretoria", "Soweto", "Nairobi", "Mombasa", "Addis Abeba", "Casablanca", "Rabat", "Marrakech", "Argel", "Orán",
  "Túnez", "Trípoli", "Jartum", "Omdurmán", "Dakar", "Abiyán", "Acra", "Kumasi", "Luanda", "Maputo",
  "Harare", "Bulawayo", "Lusaka", "Dar es Salaam", "Dodoma", "Kampala", "Kigali", "Buyumbura", "Mogadiscio", "Yibuti",
  "Asmara", "Yamena", "Niamey", "Bamako", "Uagadugú", "Conakry", "Freetown", "Monrovia", "Yamusukro", "Lomé",
  "Porto Novo", "Cotonú", "Libreville", "Brazzaville", "Yaundé", "Douala", "Bangui", "Malabo", "Windhoek", "Gaborone",
  "Maseru", "Mbabane", "Antananarivo", "Port Louis", "Victoria", "Praia", "Nuakchot", "Fez", "Tánger", "Agadir",
  "Sídney", "Melbourne", "Brisbane", "Perth", "Adelaida", "Gold Coast", "Canberra", "Newcastle", "Wollongong", "Hobart",
  "Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin", "Port Moresby", "Suva", "Honiara", "Port Vila",
  "Numea", "Apia", "Nuku'alofa", "Funafuti", "Tarawa", "Majuro", "Palikir", "Melekeok"
];
